CREATE SEQUENCE user_seq;

CREATE TABLE "user"
(
	id         BIGINT NOT NULL DEFAULT NEXTVAL('user_seq'),
	email      VARCHAR(128) NOT NULL UNIQUE,
	password   VARCHAR(128) NOT NULL,
	first_name VARCHAR(32)  NOT NULL,
	last_name  VARCHAR(32)  NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "user" ADD CONSTRAINT user_pkey PRIMARY KEY (id);