version: '2.3'

services:
  postgresql:
    image: postgres:9.6
    environment:
        POSTGRES_USER: vnext
        TZ: Asia/Jakarta
    ports:
        - 5432:5432
    # volumes:
    #     - ./volumes/postgresql/data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U vnext"]
        interval: 30s
        timeout: 30s
        retries: 3
    mem_limit: 500m

  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 30s
      timeout: 30s
      retries: 3
    mem_limit: 250m

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
    #   - kafka-data:/kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    mem_limit: 1g

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      KONG_PG_HOST: postgresql
      KONG_TRUSTED_IPS: 0.0.0.0/0
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 127.0.0.1:8444 ssl"
    depends_on:
      postgresql:
        condition: service_healthy

  account-service:
    image: account-service
    build:
      context: ./account-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.84.4.108:5432/account
    depends_on:
      postgresql:
        condition: service_healthy
        
  mail-service:
    image: mail-service
    build:
      context: ./mail-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.84.4.108:5432/account
    depends_on:
      postgresql:
        condition: service_healthy


networks:
  default:
    external:
      name: mstest
